#!/bin/sh
# SAUER_DIR should refer to the directory in which Sauerbraten is placed.
#SAUER_DIR=~/sauerbraten
#SAUER_DIR=/usr/local/lib/sauerbraten
SAUER_DIR=.

# SYSTEM_NAME should be set to the name of your operating system.
#SYSTEM_NAME=Linux
SYSTEM_NAME=`uname -s`

# MACHINE_NAME should be set to the name of your processor.
#MACHINE_NAME=i686
MACHINE_NAME=`uname -m`

case ${SYSTEM_NAME} in
Linux)
  SYSTEM_PREFIX=linux_
  ;;
*)
  echo "Your operating system does not have a pre-compiled Sauerbraten client."
  exit 1
  ;;
esac

case ${MACHINE_NAME} in
i486|i586|i686)
  MACHINE_PREFIX=
  ;;
#ppc)
#  MACHINE_PREFIX=ppc_
#  ;;
*)
  echo "Your processor does not have a pre-compiled Sauerbraten client."
  exit 1
  ;;
esac

cd ${SAUER_DIR}
exec ${SAUER_DIR}/bin_unix/${MACHINE_PREFIX}${SYSTEM_PREFIX}client $*

