// _MainMenu_EOArchive_English.java
// Generated by EnterpriseObjects palette at Dienstag, 08. November 2005 09:21 Uhr Europe/Vienna

import com.webobjects.eoapplication.*;
import com.webobjects.eocontrol.*;
import com.webobjects.eointerface.*;
import com.webobjects.eointerface.swing.*;
import com.webobjects.foundation.*;
import java.awt.*;
import javax.swing.*;
import javax.swing.border.*;
import javax.swing.table.*;
import javax.swing.text.*;

public class _MainMenu_EOArchive_English extends com.webobjects.eoapplication.EOArchive {
    MyObject _myObject0;
    com.webobjects.eointerface.swing.EOFrame _eoFrame0;
    com.webobjects.eointerface.swing.EOMatrix _nsMatrix0;
    com.webobjects.eointerface.swing.EOTextField _nsTextField0;
    javax.swing.JButton _nsButton0;
    javax.swing.JComboBox _popup0;
    javax.swing.JPanel _nsView0;
    javax.swing.JRadioButton _jRadioButton0, _jRadioButton1;

    public _MainMenu_EOArchive_English(Object owner, NSDisposableRegistry registry) {
        super(owner, registry);
    }

    protected void _construct() {
        Object owner = _owner();
        EOArchive._ObjectInstantiationDelegate delegate = (owner instanceof EOArchive._ObjectInstantiationDelegate) ? (EOArchive._ObjectInstantiationDelegate)owner : null;
        Object replacement;

        super._construct();

        _jRadioButton1 = (javax.swing.JRadioButton)_registered(new javax.swing.JRadioButton("Windowed"), "NSButtonCell1");
        _nsMatrix0 = (com.webobjects.eointerface.swing.EOMatrix)_registered(new com.webobjects.eointerface.swing.EOMatrix(2, 1, 4, 2), "NSMatrix1");
        _nsTextField0 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField2");
        _nsButton0 = (javax.swing.JButton)_registered(new javax.swing.JButton("Play!"), "NSButton");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "delegate.fullscreen")) != null)) {
            _jRadioButton0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JRadioButton)replacement;
            _replacedObjects.setObjectForKey(replacement, "_jRadioButton0");
        } else {
            _jRadioButton0 = (javax.swing.JRadioButton)_registered(new javax.swing.JRadioButton("Fullscreen"), "NSButtonCell");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "delegate")) != null)) {
            _myObject0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (MyObject)replacement;
            _replacedObjects.setObjectForKey(replacement, "_myObject0");
        } else {
            _myObject0 = (MyObject)_registered(new MyObject(), "MyObject");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "delegate.resolutions")) != null)) {
            _popup0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JComboBox)replacement;
            _replacedObjects.setObjectForKey(replacement, "_popup0");
        } else {
            _popup0 = (javax.swing.JComboBox)_registered(new javax.swing.JComboBox(), "NSPopUpButton");
        }

        _eoFrame0 = (com.webobjects.eointerface.swing.EOFrame)_registered(new com.webobjects.eointerface.swing.EOFrame(), "Window");
        _nsView0 = (JPanel)_eoFrame0.getContentPane();
    }

    protected void _awaken() {
        super._awaken();
        .addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "unhideAllApplications", ), ""));
        .addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "hide", ), ""));
        .addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "hideOtherApplications", ), ""));
        .addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "orderFrontStandardAboutPanel", ), ""));
        .addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "terminate", ), ""));

        if (_replacedObjects.objectForKey("_myObject0") == null) {
            _connect(_owner(), _myObject0, "delegate");
        }

        if (_replacedObjects.objectForKey("_popup0") == null) {
            _popup0.setModel(new javax.swing.DefaultComboBoxModel());
            _popup0.addItem("Item1");
        }
    }

    protected void _init() {
        super._init();
        _setFontForComponent(_jRadioButton1, "Lucida Grande", 13, Font.PLAIN);
        _jRadioButton0.setSize(87, 18);
        _jRadioButton0.setLocation(0, 0);
        _nsMatrix0.add(_jRadioButton0);
        _jRadioButton1.setSize(87, 18);
        _jRadioButton1.setLocation(0, 20);
        _nsMatrix0.add(_jRadioButton1);
        _setFontForComponent(_nsMatrix0, "Lucida Grande", 13, Font.PLAIN);
        _setFontForComponent(_nsTextField0, "Lucida Grande", 13, Font.PLAIN);
        _nsTextField0.setEditable(false);
        _nsTextField0.setOpaque(false);
        _nsTextField0.setText("Please choose a screen-resolution\nfor Sauerbraten:");
        _nsTextField0.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField0.setSelectable(false);
        _nsTextField0.setEnabled(true);
        _nsTextField0.setBorder(null);
        _setFontForComponent(_nsButton0, "Lucida Grande", 13, Font.PLAIN);
        _nsButton0.setMargin(new Insets(0, 2, 0, 2));
        _nsButton0.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_myObject0, "playAction", _nsButton0), ""));

        if (_replacedObjects.objectForKey("_jRadioButton0") == null) {
            _setFontForComponent(_jRadioButton0, "Lucida Grande", 13, Font.PLAIN);
        }

        if (_replacedObjects.objectForKey("_myObject0") == null) {
            _connect(_myObject0, _jRadioButton0, "fullscreen");
        }

        if (_replacedObjects.objectForKey("_myObject0") == null) {
            _connect(_myObject0, _popup0, "resolutions");
        }

        if (_replacedObjects.objectForKey("_popup0") == null) {
            _setFontForComponent(_popup0, "Lucida Grande", 13, Font.PLAIN);
        }

        if (!(_nsView0.getLayout() instanceof EOViewLayout)) { _nsView0.setLayout(new EOViewLayout()); }
        _popup0.setSize(213, 26);
        _popup0.setLocation(15, 54);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_popup0, EOViewLayout.MinYMargin);
        _nsView0.add(_popup0);
        _nsTextField0.setSize(220, 34);
        _nsTextField0.setLocation(11, 14);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField0, EOViewLayout.MinYMargin);
        _nsView0.add(_nsTextField0);
        _nsButton0.setSize(75, 26);
        _nsButton0.setLocation(156, 149);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsButton0, EOViewLayout.MinYMargin);
        _nsView0.add(_nsButton0);
        _nsMatrix0.setSize(87, 38);
        _nsMatrix0.setLocation(11, 95);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsMatrix0, EOViewLayout.MinYMargin);
        _nsView0.add(_nsMatrix0);
        _nsView0.setSize(240, 185);
        _eoFrame0.setTitle("Sauerbraten Launcher");
        _eoFrame0.setLocation(440, 487);
        _eoFrame0.setSize(240, 185);
    }
}
